### ISSUE TITLE
Better search results sorting

### ISSUE THREAD

**Issue by rafbm** [missive/emoji-picker#1]
Currently I guess the results are just arbitrarily sorted, correct? Here are a few things we should do:

- List emojis *starting* with the search query first, so **ok**_hand appears first here:

<img width="335" alt="screen shot 2016-07-26 at 11 22 36" src="https://cloud.githubusercontent.com/assets/166943/17144109/b027e1f6-5323-11e6-94b1-ad36be413ea7.png">

- Then show results with a matching *short name* before results with matching *keywords*, so co**ok**ed_rice appears before no_mouth:

<img width="335" alt="screen shot 2016-07-26 at 11 30 29" src="https://cloud.githubusercontent.com/assets/166943/17144366/812211b4-5324-11e6-9856-fd4f8a76391b.png">

- Then, sort based on alphanum order, rather than no order.

**Comment by EtienneLem** [comment]
Right now it returns the results in the `sort_order`. `search` loops on a pool of emojis and when there’s a match the emoji is added to the results.

Given we search with `indexOf` on a string like `fingers,hand,limbs,ok,ok_hand,perfect,sign`, do you have have something in mind to score results?

Maybe the search string could be sorted by field importance (`[short_name, name, keywords, emoticons].join(',')`) and we give results a score based on the `indexOf` index? The lower the more score the emoji has.

I think the first 3 results would be `:ok_hand:`, `:ok:` and `:ok_woman:`  (because they’d all have the same score, so they’d then be sorted by `sort_order`. We could also give extra points when matching the exact `short_name`, then `:ok:` would be the first result.

**Comment by rafbm** [comment]
Yes, perfect! And scratch the alphanum sorting idea.

**Comment by EtienneLem** [comment]
![screen shot 2016-07-26 at 3 31 07 pm](https://cloud.githubusercontent.com/assets/436043/17152765/3c83791c-5347-11e6-8127-9b108ad11f10.png)
![screen shot 2016-07-26 at 3 31 16 pm](https://cloud.githubusercontent.com/assets/436043/17152764/3c827b2a-5347-11e6-913a-d769885bb278.png)
![screen shot 2016-07-26 at 3 33 49 pm](https://cloud.githubusercontent.com/assets/436043/17152766/3c869a16-5347-11e6-8345-d276928227d2.png)
